# fly.toml app configuration file generated for semantic-sql-lsp on 2024-12-20T01:49:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'semantic-sql-lsp'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
